api_platform:
    title: Hello API Platform
    version: 1.0.0
    graphql:
        graphql_playground: false
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
