framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            assets/: ""
            vendor/fortawesome/font-awesome/css/: "font-awesome/css"
            vendor/fortawesome/font-awesome/js/: "font-awesome/js"
            vendor/twbs/bootstrap/dist: "bootstrap"
            vendor/twbs/bootstrap-icons/font/: "bootstrap-icons"
        excluded_patterns:
            - "*/*.scss"
            - "*/*.json"
            - "*/*.map"
            - "*/bootstrap-icons.css"
            - "*/brands.*"
            - "*/conflict-detection.*"
            - "*/fontawesome.*"
            - "*/regular.*"
            - "*/solid.*"
            - "*/v4-shims.*"
            - "*/v4-font-face.*"
            - "*/v5-font-face.*"
            - "*/all.css"
            - "*/all.min.css"
            - "*/svg-with-js.css"
            - "*/all.js"
            - "*/bootstrap-grid.*"
            - "*/bootstrap-reboot.*"
            - "*/bootstrap-utilities.*"
            - "*/bootstrap.esm.*"
            - "*/bootstrap.css"
            - "*/bootstrap.rtl.css"
            - "*/bootstrap.min.js"
            - "*/js/bootstrap.js"
        exclude_dotfiles: true
