doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        profiling_collect_backtrace: "%kernel.debug%"
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false
        entity_managers:
            default:
                mappings:
                    gedmo_loggable:
                        type: annotation
                        is_bundle: false
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
                        prefix: 'Gedmo\Loggable\Entity'
                        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                    gedmo_sortable:
                        type: annotation
                        is_bundle: false
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Sortable/Entity"
                        prefix: 'Gedmo\Sortable\Entity'
                        alias: GedmoSortable # (optional) it will default to the name set for the mapping
                    gedmo_translatable:
                        type: annotation
                        is_bundle: false
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
                        prefix: 'Gedmo\Translatable\Entity'
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                    gedmo_translator:
                        type: annotation
                        is_bundle: false
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translator/Entity"
                        prefix: 'Gedmo\Translator\Entity'
                        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                    gedmo_tree:
                        type: annotation
                        is_bundle: false
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                        prefix: 'Gedmo\Tree\Entity'
                        alias: GedmoTree # (optional) it will default to the name set for the mapping

