doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            gedmo_translatable:
                type: attribute
                prefix: 'Gedmo\Translatable\Entity'
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity'
                alias: GedmoTranslatable
                is_bundle: false
            gedmo_translator:
                type: attribute
                prefix: 'Gedmo\Translator\Entity'
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translator/Entity'
                alias: GedmoTranslator
                is_bundle: false
            gedmo_loggable:
                type: attribute
                prefix: 'Gedmo\Loggable\Entity'
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity'
                alias: GedmoLoggable
                is_bundle: false
            gedmo_tree:
                type: attribute
                prefix: 'Gedmo\Tree\Entity'
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity'
                alias: GedmoTree
                is_bundle: false
        controller_resolver:
            auto_mapping: false
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
