# Documentation available at https://pwa.spomky-labs.com/
## Please add the favicons, manifest or serviceworker sections depending on your needs.
pwa:
    asset_compiler: false # Default to true. Will change to false in 2.0.0.
    image_processor: "pwa.image_processor.gd" # 'pwa.image_processor.imagick' Or 'pwa.image_processor.gd'

    favicons:
        enabled: true
        default:
            src: images/kyg.png
            background_color: "#ffffff"
            image_scale: 95
            border_radius: 10
        dark:
            src: images/kyg.png
            background_color: "#000000"
            image_scale: 95
            border_radius: 10
        tile_color: "#526cf7"
        low_resolution: true
        use_start_image: true

    manifest:
        enabled: true
        name: "KYG Framevork"
        short_name: "KYG"
        description: "KYG Framework for Business"
        start_url: "index"
        display: "standalone"
        background_color: "#ecf0fa"
        dark_theme_color: "#19202f"
        theme_color: "#ecf0fa"
        orientation: "landscape"
        display_override: ["window-controls-overlay", "fullscreen", "minimal-ui"]
        use_credentials: true
        icons:
            - src: images/kyg.png
              sizes: [48, 72, 96, 144, 168, 192, 256, 512]

    serviceworker:
        enabled: true
        src: "sw.js"
        dest: "/js/service-worker.js"
        #workbox:
        #    background_fetch:
        #        enabled: true
        #        #success_url: "app_download_success" # Route name or URL
        #        #progress_url: "app_download_progress"
