framework:
    default_locale: "%app.locale%"
    enabled_locales: "%app.locale_list%"
    translator:
        default_path: "%kernel.project_dir%/translations"
        fallbacks: "%app.locale_list%"
        paths:
            - "%app.translations_dir%"
        providers: null
