framework:
    default_locale: ru-RU
    enabled_locales:
        - ru-RU
    translator:
        default_path: "%app.translations_dir%"
        paths:
            - "%app.modules_dir%/Administrations/Translations"
        fallbacks:
            - ru-RU
        providers:
