framework:
    default_locale: "%app.locale.default%"
    enabled_locales: "%app.locale_list%"
    translator:
        default_path: "%app.translations_dir%"
        fallbacks: "%app.locale_list%"
        providers:
