framework:
    default_locale: "%app.locale%"
    enabled_locales: "%app.locale_list%"
    translator:
        default_path: "%app.translations_dir%"
        fallbacks: "%app.locale_list%"
        paths:
            - "%app.modules_dir%/Users/Translations"
        providers: null
