framework:
    default_locale: ru-RU
    enabled_locales: "%app.locale_list%"
    translator:
        default_path: "%app.translations_dir%"
        paths:
            - "%app.modules_dir%/Administrations/Translations"
        fallbacks: "%app.locale_list%"
        providers:
