twig:
    globals:
        app_name: "%env(APP_NAME)%"

    # The default path used to load templates
    default_path: "%app.templates_dir%"

    # Pattern of file name used for cache warmer and linter
    file_name_pattern: "*.twig"
