twig:
    globals:
        app_name: "%env(APP_NAME)%"
        app_locale_list: "%app.locale_list%"
        app_date: "%env(DATE_FORMAT)%"

    # The default path used to load templates
    default_path: "%app.templates_dir%"

    # Pattern of file name used for cache warmer and linter
    file_name_pattern: "*.twig"

    # The default format options used by the date filter
    date:
        format: "%env(DATE_FORMAT)%"

        # The timezone used when formatting dates, when set to null, the timezone returned by date_default_timezone_get() is used
        #timezone: "%env(DATE_TIMEZONE)%"

    # The default format options for the number_format filter
    number_format:
        decimals: "%app.decimals%"
        decimal_point: "%app.decimal_point%"
        thousands_separator: "%app.thousands_separator%"
