twig:
    globals:
        app_name: "%app.name%"

    # The default path used to load templates
    default_path: "%app.templates_dir%"

    # Pattern of file name used for cache warmer and linter
    file_name_pattern: "*.twig"
    paths: null

    # The default format options used by the date filter
    date:
        format: "F j, Y H:i"
        interval_format: "%d days"

        # The timezone used when formatting dates, when set to null, the timezone returned by date_default_timezone_get() is used
        timezone: null

    # The default format options for the number_format filter
    number_format:
        decimals: 0
        decimal_point: "."
        thousands_separator: ","
