twig:
    globals:
        app_name: "%env(APP_NAME)%"
        app_locale_list: "%app.locale_list%"

    # The default path used to load templates
    default_path: "%app.templates_dir%"

    # Pattern of file name used for cache warmer and linter
    file_name_pattern: "*.twig"

    # The default format options used by the date filter
    date:
        format: "%env(DATE_FORMAT)%"

        # The timezone used when formatting dates, when set to null, the timezone returned by date_default_timezone_get() is used
        #timezone: "%env(DATE_TIMEZONE)%"

    # The default format options for the number_format filter
    number_format:
        decimals: "%env(int:NUMBER_FORMAT_DECIMALS)%"
        decimal_point: "%env(NUMBER_FORMAT_DECIMAL_POINT)%"
        thousands_separator: "%env(NUMBER_FORMAT_THOUSANDS_SEPARATOR)%"
