hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.php"
    prefix: /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.php"
    prefix: /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.php"
    prefix: /hwi/login

hwi_oauth_app_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.php"
    prefix: /app/hwi/login

facebook-login:
    path: /login/check-facebook

yandex-login:
    path: /login/check-yandex

google-login:
    path: /login/check-google

linkedin-login:
    path: /login/check-linkedin

mailru-login:
    path: /login/check-mailru

odnoklassniki-login:
    path: /login/check-odnoklassniki

x-twitter-login:
    path: /login/check-xtwitter

vkontakte-login:
    path: /login/check-vkontakte

github-login:
    path: /login/check-github

amazon-login:
    path: /login/check-amazon

instagram-login:
    path: /login/check-instagram

twitch-login:
    path: /login/check-twitch

yahoo-login:
    path: /login/check-yahoo

spotify-login:
    path: /login/check-spotify

trello-login:
    path: /login/check-trello

dropbox-login:
    path: /login/check-dropbox

flickr-login:
    path: /login/check-flickr

windows-live-login:
    path: /login/check-windows-live

facebook-app-login:
    path: /app/login/check-facebook

yandex-app-login:
    path: /app/login/check-yandex

google-app-login:
    path: /app/login/check-google

linkedin-app-login:
    path: /app/login/check-linkedin

mailru-app-login:
    path: /app/login/check-mailru

odnoklassniki-app-login:
    path: /app/login/check-odnoklassniki

x-twitter-app-login:
    path: /app/login/check-xtwitter

vkontakte-app-login:
    path: /app/login/check-vkontakte

github-app-login:
    path: /app/login/check-github

amazon-app-login:
    path: /app/login/check-amazon

instagram-app-login:
    path: /app/login/check-instagram

twitch-app-login:
    path: /app/login/check-twitch

yahoo-app-login:
    path: /app/login/check-yahoo

spotify-app-login:
    path: /app/login/check-spotify

trello-app-login:
    path: /app/login/check-trello

dropbox-app-login:
    path: /app/login/check-dropbox

flickr-app-login:
    path: /app/login/check-flickr

windows-live-app-login:
    path: /app/login/check-windows-live
