parameters:
    app.name: "KYG Framework for Business"
    app.name.language: en
    app.locale: ru-RU
    app.locale_list:
        - en-US
        - ru-RU
    app.dataformat: null
    app.timeformat: null
    app.separator: " "
    app.datatimeformat: "F j, Y H:i"
    app.timezone: null
    app.decimals: 0
    app.decimal_point: .
    app.thousands_separator: ","
    app.email: mailer@your-domain.com
    app.email.user: "Acme Mail Bot"
