parameters:
    roles:
        ROLE_ADMIN:
            label: "roles.admin"
            domain: "roles"
        ROLE_EMPLOYEE:
            label: "roles.employee"
            domain: "roles"
        ROLE_SUPERADMIN:
            label: "roles.superadmin"
            domain: "roles"
        ROLE_USER:
            label: "reles.user"
            domain: "roles"

security:
    role_hierarchy:
        ROLE_SUPERADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_EMPLOYEE
        ROLE_EMPLOYEE: ROLE_USER
