parameters:
    app.name: "KYG Framework for Business"
    app.locale.default: "ru-RU"
    app.locale_list:
        - "ru-RU"
    app.timezone: null
    app.dataformat: null
    app.timeformat: null
    app.separator: " "
    app.datatimeformat: "F j, Y H:i"
    app.decimals: 0
    app.decimal_point: "."
    app.thousands_separator: ","
    app.surname_sign: true
    app.email: "mailer@your-domain.com"
    app.email.user: "Acme Mail Bot"
