parameters:
    app.timezone: null
    app.locale.default: "en"
    app.locale_list:
        - "ru-RU"
    app.surname_sign: true
    app.email: "mailer@your-domain.com"
    app.email.user: "Acme Mail Bot"
