Effect:
    - blind
    - bounce
    - clip
    - drop
    - fold
    - highlight
    - puff
    - pulsate
    - scale
    - shake
    - size
    - slide
    - transfer
LangCKEditor:
    - af
    - ar
    - ast
    - az
    - bg
    - bn
    - bs
    - ca
    - cs
    - da
    - de
    - de-ch
    - el
    - en-au
    - en-gb
    - eo
    - es
    - es-co
    - et
    - eu
    - fa
    - fi
    - fr
    - gl
    - gu
    - he
    - hi
    - hr
    - hu
    - hy
    - id
    - it
    - ja
    - jv
    - kk
    - km
    - kn
    - ko
    - ku
    - lt
    - lv
    - ms
    - nb
    - ne
    - nl
    - 'no'
    - oc
    - pl
    - pt
    - pt-br
    - ro
    - ru
    - si
    - sk
    - sl
    - sq
    - sr
    - sr-latn
    - sv
    - th
    - tk
    - tr
    - tt
    - ug
    - uk
    - ur
    - uz
    - vi
    - zh
    - zh-cn
LangData:
    - af
    - ar
    - ar-DZ
    - az
    - be
    - bg
    - bs
    - ca
    - cs
    - cy-GB
    - da
    - de
    - de-AT
    - el
    - en-AU
    - en-GB
    - en-NZ
    - eo
    - es
    - et
    - eu
    - fa
    - fi
    - fo
    - fr
    - fr-CA
    - fr-CH
    - gl
    - he
    - hi
    - hr
    - hu
    - hy
    - id
    - is
    - it
    - it-CH
    - ja
    - ka
    - kk
    - km
    - ko
    - ky
    - lb
    - lt
    - lv
    - mk
    - ml
    - ms
    - nb
    - nl
    - nl-BE
    - nn
    - 'no'
    - pl
    - pt
    - pt-BR
    - rm
    - ro
    - ru
    - sk
    - sl
    - sq
    - sr
    - sr-SR
    - sv
    - ta
    - ta
    - tj
    - tr
    - uk
    - vi
    - zh-CN
    - zh-HK
    - zh-TW
Theme:
    - base
    - black-tie
    - blitzer
    - cupertino
    - dark-hive
    - dot-luv
    - eggplant
    - excite-bike
    - flick
    - hot-sneaks
    - humanity
    - le-frog
    - mint-choc
    - overcast
    - pepper-grinder
    - redmond
    - smoothness
    - south-street
    - start
    - sunny
    - swanky-purse
    - trontastic
    - ui-darkness
    - ui-lightness
    - vader