controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_attributes:
    resource: "../extensions/Modules/*/Controller/"
    type: attribute
