App_controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
Install_controllers:
    resource:
        path: ../modules/Install/Controller/
        namespace: App\Modules\Install\Controller
    type: attribute
