# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.modules_dir: "%kernel.project_dir%/modules"
    app.public_dir: "%kernel.project_dir%/public"
    app.additions_dir: "%app.public_dir%/additions"
    app.config_dir: "%app.public_dir%/config"
    app.translations_dir: "%app.public_dir%/translations"
    app.media_dir: "%app.public_dir%/media"
    app.var_dir: "%kernel.project_dir%/var"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/EventSubscriber/"
            - "../src/Kernel.php"
    App\Modules\:
        resource: "../modules/"
        exclude:
            - "../modules/**/DependencyInjection/"
            - "../modules/**/Entity/"
            - "../modules/**/EventSubscriber/"
            - "../modules/**/Service/"
    App\Additions\:
        resource: "../public/additions/"
        exclude:
            - "../public/additions/**/DependencyInjection/"
            - "../public/additions/**/Entity/"
            - "../public/additions/**/EventSubscriber/"
            - "../public/additions/**/Service/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Squirrel\TwigPhpSyntax\PhpSyntaxExtension:
        tags: [twig.extension]

imports:
    - { resource: "../public/config/*.yaml" }
    - { resource: "../modules/*/Resources/config/*.yaml" }
    - { resource: "../public/additions/*/Resources/config/*.yaml" }
