# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.config_dir: "%kernel.project_dir%/config"
    app.config_packages_dir: "%app.config_dir%/packages"
    app.modules_dir: "%kernel.project_dir%/modules"
    app.public_dir: "%kernel.project_dir%/public"
    app.additions_dir: "%app.public_dir%/additions"
    app.public_config_dir: "%app.public_dir%/config"
    app.images_dir: "%app.public_dir%/images"
    app.translations_dir: "%app.public_dir%/translations"
    app.templates_dir: "%kernel.project_dir%/templates"
    app.var_dir: "%kernel.project_dir%/var"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    event_subscribers:
        namespace: 'App\EventSubscriber\'
        resource: "../src/EventSubscriber/"
        tags: [event_subscriber]
    security_emailverifier:
        class: 'App\Modules\Users\Security\EmailVerifier'
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
    App\Modules\:
        resource: "../modules/"
        exclude:
            - "../modules/**/DependencyInjection/"
            - "../modules/**/Entity/"
            - "../modules/**/Service/"
    App\Additions\:
        resource: "../public/additions/"
        exclude:
            - "../public/additions/**/DependencyInjection/"
            - "../public/additions/**/Entity/"
            - "../public/additions/**/Service/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\DependencyInjection\YamlEnvVarLoader:
        tags: [container.env_var_loader]
    App\Twig\AppTwigExtension:
        tags: [twig.extension]
    Squirrel\TwigPhpSyntax\PhpSyntaxExtension:
        tags: [twig.extension]

imports:
    - {resource: "../public/config/*.yaml", ignore_errors: true}
    - {resource: "../modules/*/Config/*.yaml"}
    - {resource: "../public/additions/*/Config/*.yaml"}
