# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
    App\Modules\:
        resource: "../modules/"
        exclude:
            - "../modules/*/DependencyInjection/"
            - "../modules/*/Entity/"
            - "../modules/*/Resources/"
    App\Additions\:
        resource: "../public/additions/"
        exclude:
            - "../public/additions/*/DependencyInjection/"
            - "../public/additions/*/Entity/"
            - "../public/additions/*/Resources/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Gedmo
    Gedmo\:
        resource: "../vendor/gedmo/doctrine-extensions/src/"
        exclude:
            - "../vendor/gedmo/doctrine-extensions/src/Mapping/"
            - "../vendor/gedmo/doctrine-extensions/src/ReferenceIntegrity/"
            - "../vendor/gedmo/doctrine-extensions/src/References/"

    # Attribute mapping driver for the Doctrine Extension listeners
    gedmo.mapping.driver.attribute:
        class: Gedmo\Mapping\Driver\AttributeReader

    # Gedmo Blameable Extension Listener
    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: "doctrine.event_listener", event: "prePersist" }
            - { name: "doctrine.event_listener", event: "onFlush" }
            - { name: "doctrine.event_listener", event: "loadClassMetadata" }
        calls:
            - [setAnnotationReader, ["@gedmo.mapping.driver.attribute"]]

    # Gedmo IP Traceable Extension Listener
    gedmo.listener.ip_traceable:
        class: Gedmo\IpTraceable\IpTraceableListener
        tags:
            - { name: "doctrine.event_listener", event: "prePersist" }
            - { name: "doctrine.event_listener", event: "onFlush" }
            - { name: "doctrine.event_listener", event: "loadClassMetadata" }
        calls:
            - [setAnnotationReader, ["@gedmo.mapping.driver.attribute"]]

    # Gedmo Loggable Extension Listener
    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: "doctrine.event_listener", event: "onFlush" }
            - { name: "doctrine.event_listener", event: "loadClassMetadata" }
            - { name: "doctrine.event_listener", event: "postPersist" }
        calls:
            - [setAnnotationReader, ["@gedmo.mapping.driver.attribute"]]

    # Gedmo Sluggable Extension Listener
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: "doctrine.event_listener", event: "onFlush" }
            - { name: "doctrine.event_listener", event: "loadClassMetadata" }
            - { name: "doctrine.event_listener", event: "prePersist" }
        calls:
            - [setAnnotationReader, ["@gedmo.mapping.driver.attribute"]]

    # Gedmo Soft Deleteable Extension listener
    gedmo.listener.soft_deleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: "doctrine.event_listener", event: "loadClassMetadata" }
            - { name: "doctrine.event_listener", event: "onFlush" }
        calls:
            - [setAnnotationReader, ["@gedmo.mapping.driver.attribute"]]
            - [setClock, ["@clock"]]

    # Gedmo Sortable Extension listener
    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: "doctrine.event_listener", event: "onFlush" }
            - { name: "doctrine.event_listener", event: "loadClassMetadata" }
            - { name: "doctrine.event_listener", event: "prePersist" }
            - { name: "doctrine.event_listener", event: "postPersist" }
            - { name: "doctrine.event_listener", event: "preUpdate" }
            - { name: "doctrine.event_listener", event: "postRemove" }
            - { name: "doctrine.event_listener", event: "postFlush" }
        calls:
            - [setAnnotationReader, ["@gedmo.mapping.driver.attribute"]]

    # Gedmo Timestampable Extension Listener
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: "doctrine.event_listener", event: "prePersist" }
            - { name: "doctrine.event_listener", event: "onFlush" }
            - { name: "doctrine.event_listener", event: "loadClassMetadata" }
        calls:
            - [setAnnotationReader, ["@gedmo.mapping.driver.attribute"]]
            - [setClock, ["@clock"]]

    # Gedmo Translatable Extension Listener
    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: "doctrine.event_listener", event: "postLoad" }
            - { name: "doctrine.event_listener", event: "postPersist" }
            - { name: "doctrine.event_listener", event: "preFlush" }
            - { name: "doctrine.event_listener", event: "onFlush" }
            - { name: "doctrine.event_listener", event: "loadClassMetadata" }
        calls:
            - [setAnnotationReader, ["@gedmo.mapping.driver.attribute"]]
            - [setDefaultLocale, ["%kernel.default_locale%"]]

    # Gedmo Tree Extension Listener
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: "doctrine.event_listener", event: "prePersist" }
            - { name: "doctrine.event_listener", event: "preUpdate" }
            - { name: "doctrine.event_listener", event: "preRemove" }
            - { name: "doctrine.event_listener", event: "onFlush" }
            - { name: "doctrine.event_listener", event: "loadClassMetadata" }
            - { name: "doctrine.event_listener", event: "postPersist" }
            - { name: "doctrine.event_listener", event: "postUpdate" }
            - { name: "doctrine.event_listener", event: "postRemove" }
        calls:
            - [setAnnotationReader, ["@gedmo.mapping.driver.attribute"]]

    # Gedmo Uploadable Extension Listener
    gedmo.listener.uploadable:
        class: Gedmo\Uploadable\UploadableListener
        tags:
            - { name: "doctrine.event_listener", event: "loadClassMetadata" }
            - { name: "doctrine.event_listener", event: "preFlush" }
            - { name: "doctrine.event_listener", event: "onFlush" }
            - { name: "doctrine.event_listener", event: "postFlush" }
        calls:
            - [setAnnotationReader, ["@gedmo.mapping.driver.attribute"]]

imports:
    - { resource: "../modules/*/Resources/config/*.*" }
    - { resource: "../public/additions/*/Resources/config/*.*" }
    - { resource: "../public/config/*.yaml" }
