parameters:
    app.name: "KYG Framework for Business"
    app.locale_list:
        - "en-US"
        - "ru-RU"
    app.dataformat: null
    app.timeformat: null
    app.separator: " "
    app.datatimeformat: "F j, Y H:i"
    app.timezone: null
    app.decimals: 0
    app.decimal_point: "."
    app.thousands_separator: ","
