doctrine:
    orm:
        mappings:
            User:
                type: attribute
                is_bundle: false
                dir: "%app.modules_dir%/User/Entity"
                prefix: 'App\Modules\User\Entity'
                alias: User
