parameters:
    app.db.url: "%env(resolve:DATABASE_URL)%"
    app.secret: "%env(APP_SECRET)%"
    app.default_locale: en
    app.locale:
        - en
        - ru_RU
        - uk_UA
    app.interface:
        Themes: "start"
        Effects: "blind"
    app.install: false
