doctrine:
    orm:
        mappings:
            Users:
                type: attribute
                is_bundle: false
                dir: "%app.modules_dir%/Users/Entity"
                prefix: 'App\Modules\Users\Entity'
                alias: Users
