framework:
    workflows:
        user_status:
            type: "state_machine"
            marking_store:
                type: "method"
                property: "status"
            supports:
                - App\Modules\Users\Entity\Users
            initial_marking: !php/enum App\Modules\Users\Enum\Status::New
            places: !php/enum App\Modules\Users\Enum\Status
            transitions:
                validated:
                    from: !php/enum App\Modules\Users\Enum\Status::New
                    to: !php/enum App\Modules\Users\Enum\Status::Validated
                pending:
                    from: !php/enum App\Modules\Users\Enum\Status::Validated
                    to: !php/enum App\Modules\Users\Enum\Status::Pending
                active:
                    from:
                        - !php/enum App\Modules\Users\Enum\Status::New
                        - !php/enum App\Modules\Users\Enum\Status::Pending
                        - !php/enum App\Modules\Users\Enum\Status::Inactive
                        - !php/enum App\Modules\Users\Enum\Status::Disabled
                        - !php/enum App\Modules\Users\Enum\Status::Validated
                    to: !php/enum App\Modules\Users\Enum\Status::Active
                inactive:
                    from: !php/enum App\Modules\Users\Enum\Status::Active
                    to: !php/enum App\Modules\Users\Enum\Status::Inactive
                banned:
                    from: !php/enum App\Modules\Users\Enum\Status::Active
                    to: !php/enum App\Modules\Users\Enum\Status::Banned
                deleted:
                    from:
                        - !php/enum App\Modules\Users\Enum\Status::New
                        - !php/enum App\Modules\Users\Enum\Status::Pending
                        - !php/enum App\Modules\Users\Enum\Status::Active
                        - !php/enum App\Modules\Users\Enum\Status::Inactive
                        - !php/enum App\Modules\Users\Enum\Status::Banned
                        - !php/enum App\Modules\Users\Enum\Status::Disabled
                        - !php/enum App\Modules\Users\Enum\Status::Validated
                    to: !php/enum App\Modules\Users\Enum\Status::Deleted
                disabled:
                    from:
                        - !php/enum App\Modules\Users\Enum\Status::New
                        - !php/enum App\Modules\Users\Enum\Status::Pending
                        - !php/enum App\Modules\Users\Enum\Status::Active
                        - !php/enum App\Modules\Users\Enum\Status::Inactive
                        - !php/enum App\Modules\Users\Enum\Status::Banned
                        - !php/enum App\Modules\Users\Enum\Status::Validated
                    to: !php/enum App\Modules\Users\Enum\Status::Disabled
                not_banned:
                    from: !php/enum App\Modules\Users\Enum\Status::Banned
                    to: !php/enum App\Modules\Users\Enum\Status::Disabled
                not_deleted:
                    from: !php/enum App\Modules\Users\Enum\Status::Deleted
                    to: !php/enum App\Modules\Users\Enum\Status::Disabled
