<?php
/****************************************************************************************
 * @Project    KYG Framework
 * @Version    1.0
 * @Data       01.01.2024 г.
 *
 * @Copyright  (C) 2024 Kataev Yaroslav Georgievich 
 * @E-mail     yaroslaw74@gmail.com
 * @License    GNU General Public License version 3 or later; see LICENSE.txt
 ***************************************************************************************/
declare(strict_types = 1);

namespace KYG\templates;

class TemplateHTML extends \Smarty {

	protected $LanguageHTML;
	public $Themes = array();
	public $NameHost;
	public $TimeZone = array();
	public $DataForm = array(
		'YYYY.MM.DD' => 'Y.m.d',
		'YYYY-MM-DD' => 'Y-m-d', 
		'YYYY/MM/DD' => 'Y/m/d', 
		'yyyy.mm.dd' => 'Y.n.j', 
		'yyyy-mm-dd' => 'Y-n-j',
		'yyyy/mm/dd' => 'Y/n/j',
		'YYYY.DD.MM' => 'Y.d.m',
		'YYYY-DD-MM' => 'Y-d-m', 
		'YYYY/DD/MM' => 'Y/d/m', 
		'yyyy.dd.mm' => 'Y.j.n',
		'yyyy-dd-mm' => 'Y-j-n',
		'YYYY/dd/mm' => 'Y/j/n',
		'dd.mm.yyyy' => 'j.n.Y',
		'dd-mm-yyyy' => 'j-n-Y',
		'dd/mm/yyyy' => 'j/n/Y',
		'DD.MM.YYYY' => 'd.m.Y', 
		'DD-MM-YYYY' => 'd-m-Y', 
		'DD/MM/YYYY' => 'd/m/Y', 
		'mm.dd.yyyy' => 'n.j.Y',
		'mm-dd-yyyy' => 'n-j-Y',
		'mm/dd/yyyy' => 'n/j/Y',
		'MM.DD.YYYY' => 'm.d.Y', 
		'MM-DD-YYYY' => 'm-d-Y', 
		'MM/DD/YYYY' => 'm/d/Y'
	);
	public $TimeForm = array(
		'HH:MM:SS'       => 'H:i:s',
		'HH.MM.SS'       => 'H.i.s',
		'HH,MM,SS'       => 'H,i,s',
		'HH:MM:SS am/pm' => 'h:i:s a',
		'HH.MM.SS am/pm' => 'h.i.s a',
		'HH,MM,SS am/pm' => 'h,i,s a',
		'HH:MM:SS AM/PM' => 'h:i:s A',
		'HH.MM.SS AM/PM' => 'h.i.s A',
		'HH,MM,SS AM/PM' => 'h,i,s A',
		'hh:mm:ss'       => 'G:i:s',
		'hh.mm.ss'       => 'G.i.s',
		'hh,mm,ss'       => 'G,i,s',
		'hh:mm:ss am/pm' => 'g:i:s a',
		'hh.mm.ss am/pm' => 'g.i.s a',
		'hh,mm,ss am/pm' => 'g,i,s a',
		'hh:mm:ss AM/PM' => 'g:i:s A',
		'hh.mm.ss AM/PM' => 'g.i.s A',
		'hh,mm,ss AM/PM' => 'g,i,s A'
	);
	public $LanguageList = array(
		'af-ZA'          => array('Afrikaans (Suid-Afrika)', 'af', 'za'),
		'am-ET'          => array('አማርኛ (ኢትዮጵያ)', 'am', 'et'),
		'ar-AE'          => array('العربية (الإمارات العربية المتحدة)', 'ar', 'ae'),
		'ar-BH'          => array('العربية (البحرين)', 'ar', 'bh'),
		'ar-DZ'          => array('العربية (الجزائر)', 'ar', 'dz'),
		'ar-EG'          => array('العربية (مصر)', 'ar', 'eg'),
		'ar-IQ'          => array('العربية (العراق)', 'ar', 'iq'),
		'ar-JO'          => array('العربية (الأردن)', 'ar', 'jo'),
		'ar-KW'          => array('العربية (الكويت)', 'ar', 'kw'),
		'ar-LB'          => array('العربية (لبنان)', 'ar', 'lb'),
		'ar-LY'          => array('العربية (ليبيا)', 'ar', 'ly'),
		'ar-MA'          => array('العربية (المملكة المغربية)', 'ar', 'ma'),
		'ar-OM'          => array('العربية (عمان)', 'ar', 'om'),
		'ar-QA'          => array('العربية (قطر)', 'ar', 'qa'),
		'ar-SA'          => array('العربية (المملكة العربية السعودية)', 'ar', 'sa'),
		'ar-SY'          => array('العربية (سوريا)', 'ar', 'sy'),
		'ar-TN'          => array('العربية (تونس)', 'ar', 'tn'),
		'ar-YE'          => array('العربية (اليمن)', 'ar', 'ye'),
		'arn-CL'         => array('Mapudungun (Chile)', 'arn', 'cl'),
		'as-IN'          => array('অসমীয়া (ভাৰত)', 'as', 'in'),
		'az-Cyrl-AZ'     => array('Азәрбајҹан дили (Азәрбајҹан)', 'az', 'az'),
		'az-Latn-AZ'     => array('Azərbaycan dili (Azərbaycan)', 'az', 'az'),
		'ba-RU'          => array('Башҡорт (Рәсәй)', 'ba', 'ru'),
		'be-BY'          => array('Беларуская (Беларусь)', 'be', 'by'),
		'bg-BG'          => array('български (България)', 'bg', 'bg'),
		'bn-BD'          => array('বাংলা (বাংলাদেশ)', 'bn', 'bd'),
		'bn-IN'          => array('বাংলা (ভারত)', 'bn', 'in'),
		'bo-CN'          => array('བོད་ཡིག (ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ།)', 'bo', 'cn'),
		'br-FR'          => array('brezhoneg (Frañs)', 'br', 'fr'),
		'bs-Cyrl-BA'     => array('босански (Босна и Херцеговина)', 'bs', 'ba'),
		'bs-Latn-BA'     => array('bosanski (Bosna i Hercegovina)', 'bs', 'ba'),
		'ca-ES'          => array('Català (Català)', 'ca', 'es'),
		'ca-ES-valencia' => array('Valencià (Espanya)', 'ca', 'es'),
		'chr-Cher-US'    => array('ᏣᎳᎩ (ᏣᎳᎩ)', 'chr', 'us'),
		'co-FR'          => array('Corsu (Francia)', 'co', 'fr'),
		'cs-CZ'          => array('čeština (Česká republika)', 'cs', 'cz'),
		'cy-GB'          => array('Cymraeg (Y Deyrnas Unedig)', 'cy', 'gb'),
		'da-DK'          => array('dansk (Danmark)', 'da', 'dk'),
		'de-AT'          => array('Deutsch (Österreich)', 'de', 'at'),
		'de-CH'          => array('Deutsch (Schweiz)', 'de', 'ch'),
		'de-DE'          => array('Deutsch (Deutschland)', 'de', 'de'),
		'de-LI'          => array('Deutsch (Liechtenstein)', 'de', 'li'),
		'de-LU'          => array('Deutsch (Luxemburg)', 'de', 'lu'),
		'dsb-DE'         => array('dolnoserbšćina (Nimska)', 'dsb', 'de'),
		'dv-MV'          => array('ދިވެހިބަސް (ދިވެހި ރާއްޖެ)', 'dv', 'mv'),
		'el-GR'          => array('Ελληνικά (Ελλάδα)', 'el', 'gr'),
		'en-AU'          => array('English (Australia)', 'en', 'au'),
		'en-BZ'          => array('English (Belize)', 'en', 'bz'),
		'en-CA'          => array('English (Canada)', 'en', 'ca'),
		'en-GB'          => array('English (United Kingdom)', 'en', 'gb'),
		'en-HK'          => array('English (Hong Kong)', 'en', 'hk'),
		'en-IE'          => array('English (Ireland)', 'en', 'ie'),
		'en-IN'          => array('English (India)', 'en', 'in'),
		'en-JM'          => array('English (Jamaica)', 'en', 'jm'),
		'en-MY'          => array('English (Malaysia)', 'en', 'my'),
		'en-NZ'          => array('English (New Zealand)', 'en', 'nz'),
		'en-PH'          => array('English (Philippines)', 'en', 'ph'),
		'en-SG'          => array('English (Singapore)', 'en', 'sg'),
		'en-TT'          => array('English (Trinidad and Tobago)', 'en', 'tt'),
		'en-US'          => array('English (United States)', 'en', 'us'),
		'en-ZA'          => array('English (South Africa)', 'en', 'za'),
		'en-ZW'          => array('English (Zimbabwe)', 'en', 'zw'),
		'es-AR'          => array('español (Argentina)', 'es', 'ar'),
		'es-BO'          => array('español (Bolivia)', 'es', 'bo'),
		'es-CL'          => array('español (Chile)', 'es', 'cl'),
		'es-CO'          => array('español (Colombia)', 'es', 'co'),
		'es-CR'          => array('español (Costa Rica)', 'es', 'cr'),
		'es-DO'          => array('español (República Dominicana)', 'es', 'do'),
		'es-EC'          => array('español (Ecuador)', 'es', 'ec'),
		'es-ES'          => array('español (España, alfabetización internacional)', 'es', 'es'),
		'es-GT'          => array('español (Guatemala)', 'es', 'gt'),
		'es-HN'          => array('español (Honduras)', 'es', 'hn'),
		'es-MX'          => array('español (México)', 'es', 'mx'),
		'es-NI'          => array('español (Nicaragua)', 'es', 'ni'),
		'es-PA'          => array('español (Panamá)', 'es', 'pa'),
		'es-PE'          => array('español (Perú)', 'es', 'pe'),
		'es-PR'          => array('español (Puerto Rico)', 'es', 'pr'),
		'es-PY'          => array('español (Paraguay)', 'es', 'py'),
		'es-SV'          => array('español (El Salvador)', 'es', 'sv'),
		'es-US'          => array('español (Estados Unidos)', 'es', 'us'),
		'es-UY'          => array('español (Uruguay)', 'es', 'uy'),
		'es-VE'          => array('español (Republica Bolivariana de Venezuela)', 'es', 've'),
		'et-EE'          => array('eesti (Eesti)', 'et', 'ee'),
		'eu-ES'          => array('euskara (euskara)', 'eu', 'es'),
		'fa-IR'          => array('فارسى (ایران)', 'fa', 'ir'),
		'ff-Latn-SN'     => array('Fulah (Sénégal)', 'ff', 'sn'),
		'fi-FI'          => array('suomi (Suomi)', 'fi', 'fi'),
		'fil-PH'         => array('Filipino (Pilipinas)', 'fil', 'ph'),
		'fo-FO'          => array('føroyskt (Føroyar)', 'fo', 'fo'),
		'fr-BE'          => array('français (Belgique)', 'fr', 'be'),
		'fr-CA'          => array('français (Canada)', 'fr', 'ca'),
		'fr-CD'          => array('français (Congo [RDC])', 'fr', 'cd'),
		'fr-CH'          => array('français (Suisse)', 'fr', 'ch'),
		'fr-CI'          => array('français (Côte d’Ivoire)', 'fr', 'ci'),
		'fr-CM'          => array('français (Cameroun)', 'fr', 'cm'),
		'fr-FR'          => array('français (France)', 'fr', 'fr'),
		'fr-HT'          => array('français (Haïti)', 'fr', 'ht'),
		'fr-LU'          => array('français (Luxembourg)', 'fr', 'lu'),
		'fr-MA'          => array('français (Maroc)', 'fr', 'ma'),
		'fr-MC'          => array('français (Principauté de Monaco)', 'fr', 'mc'),
		'fr-ML'          => array('français (Mali)', 'fr', 'ml'),
		'fr-RE'          => array('français (Réunion)', 'fr', 're'),
		'fr-SN'          => array('français (Sénégal)', 'fr', 'sn'),
		'fy-NL'          => array('Frysk (Nederlân)', 'fy', 'nl'),
		'ga-IE'          => array('Gaeilge (Éire)', 'ga', 'ie'),
		'gd-GB'          => array('Gàidhlig (An Rìoghachd Aonaichte)', 'gd', 'gb'),
		'gl-ES'          => array('galego (galego)', 'gl', 'es'),
		'gn-PY'          => array('Guarani (Paraguái)', 'gn', 'py'),
		'gsw-FR'         => array('Elsässisch (Frànkrisch)', 'gsw', 'fr'),
		'gu-IN'          => array('ગુજરાતી (ભારત)', 'gu', 'in'),
		'ha-Latn-NG'     => array('Hausa (Nijeriya)', 'ha', 'ng'),
		'haw-US'         => array('Hawaiʻi (ʻAmelika)', 'haw', 'us'),
		'he-IL'          => array('עברית (ישראל)', 'he', 'il'),
		'hi-IN'          => array('हिंदी (भारत)', 'hi', 'in'),
		'hr-BA'          => array('hrvatski (Bosna i Hercegovina)', 'hr', 'ba'),
		'hr-HR'          => array('hrvatski (Hrvatska)', 'hr', 'hr'),
		'hsb-DE'         => array('hornjoserbšćina (Němska)', 'hsb', 'de'),
		'hu-HU'          => array('magyar (Magyarország)', 'hu', 'hu'),
		'hy-AM'          => array('Հայերեն (Հայաստան)', 'hy', 'am'),
		'id-ID'          => array('Bahasa Indonesia (Indonesia)', 'id', 'id'),
		'ig-NG'          => array('Igbo (Nigeria)', 'ig', 'ng'),
		'ii-CN'          => array('ꆈꌠꁱꂷ (ꍏꉸꏓꂱꇭꉼꇩ)', 'ii', 'cn'),
		'is-IS'          => array('íslenska (Ísland)', 'is', 'is'),
		'it-CH'          => array('italiano (Svizzera)', 'it', 'ch'),
		'it-IT'          => array('italiano (Italia)', 'it', 'it'),
		'iu-Cans-CA'     => array('ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕᒥ)', 'iu', 'ca'),
		'iu-Latn-CA'     => array('Inuktitut (Kanatami)', 'iu', 'ca'),
		'ja-JP'          => array('日本語 (日本)', 'ja', 'jp'),
		'jv-Latn-ID'     => array('Basa Jawa (Indonesia)', 'jv', 'id'),
		'ka-GE'          => array('ქართული (საქართველო)', 'ka', 'ge'),
		'kk-KZ'          => array('Қазақ (Қазақстан)', 'kk', 'kz'),
		'kl-GL'          => array('kalaallisut (Kalaallit Nunaat)', 'kl', 'gl'),
		'km-KH'          => array('ភាសាខ្មែរ (កម្ពុជា)', 'km', 'kh'),
		'ko-KR'          => array('한국어(대한민국)', 'ko', 'kr'),
		'kok-IN'         => array('कोंकणी (भारत)', 'kok', 'in'),
		'ku-Arab-IQ'     => array('کوردیی ناوەڕاست (کوردستان)', 'ku', 'iq'),
		'ky-KG'          => array('Кыргыз (Кыргызстан)', 'ky', 'kg'),
		'lb-LU'          => array('Lëtzebuergesch (Lëtzebuerg)', 'lb', 'lu'),
		'lo-LA'          => array('ພາສາລາວ (ສປປ ລາວ)', 'lo', 'la'),
		'lt-LT'          => array('lietuvių (Lietuva)', 'lt', 'lt'),
		'lv-LV'          => array('latviešu (Latvija)', 'lv', 'lv'),
		'mg-MG'          => array('Malagasy (Madagasikara)', 'mg', 'mg'),
		'mi-NZ'          => array('Reo Māori (Aotearoa)', 'mi', 'nz'),
		'mk-MK'          => array('македонски јазик (Македонија)', 'mk', 'mk'),
		'ml-IN'          => array('മലയാളം (ഭാരതം)', 'ml', 'in'),
		'mn-MN'          => array('Монгол хэл (Монгол улс)', 'mn', 'mn'),
		'mn-Mong-CN'     => array('ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ (ᠪᠦᠭᠦᠳᠡ ᠨᠠᠢᠷᠠᠮᠳᠠᠬᠤ ᠳᠤᠮᠳᠠᠳᠤ ᠠᠷᠠᠳ ᠣᠯᠣᠰ)', 'mn', 'cn'),
		'mn-Mong-MN'     => array('ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ (ᠮᠤᠨᠭᠭᠤᠯ ᠣᠯᠣᠰ)', 'mn', 'mn'),
		'moh-CA'         => array('Kanien`kéha', 'moh', 'ca'),
		'mr-IN'          => array('मराठी (भारत)', 'mr', 'in'),
		'ms-BN'          => array('Bahasa Melayu (Brunei Darussalam)', 'ms', 'bn'),
		'ms-MY'          => array('Bahasa Melayu (Malaysia)', 'ms', 'my'),
		'mt-MT'          => array('Malti (Malta)', 'mt', 'mt'),
		'my-MM'          => array('ဗမာ (မြန်မာ)', 'my', 'mm'),
		'nb-NO'          => array('norsk, bokmål (Norge)', 'nb', 'no'),
		'ne-IN'          => array('नेपाली (भारत)', 'ne', 'in'),
		'ne-NP'          => array('नेपाली (नेपाल)', 'ne', 'np'),
		'nl-BE'          => array('Nederlands (België)', 'nl', 'be'),
		'nl-NL'          => array('Nederlands (Nederland)', 'nl', 'nl'),
		'nn-NO'          => array('norsk, nynorsk (Noreg)', 'nn', 'no'),
		'nqo-GN'         => array('ߒߞߏ (ߖߌ߬ߣߍ߬ ߞߊ߲ߓߍ߲)', 'nqo', 'gn'),
		'nso-ZA'         => array('Sesotho sa Leboa (Afrika Borwa)', 'nzo', 'za'),
		'oc-FR'          => array('Occitan (França)', 'oc', 'fr'),
		'om-ET'          => array('Oromoo (Itoophiyaa)', 'om', 'et'),
		'or-IN'          => array('ଓଡ଼ିଆ (ଭାରତ)', 'or', 'in'),
		'pa-Arab-PK'     => array('پنجابی (پاکستان)', 'pa', 'pk'),
		'pa-IN'          => array('ਪੰਜਾਬੀ (ਭਾਰਤ)', 'pa', 'in'),
		'pl-PL'          => array('polski (Polska)', 'pl', 'pl'),
		'prs-AF'         => array('درى (افغانستان)', 'prs', 'af'),
		'pt-AO'          => array('português (Angola)', 'pt', 'ao'),
		'pt-BR'          => array('português (Brasil)', 'pt', 'br'),
		'pt-PT'          => array('português (Portugal)', 'pt', 'pt'),
		'qut-GT'         => array('K`iche` (Guatemala)', 'qut', 'gt'),
		'quz-BO'         => array('runasimi (Qullasuyu)', 'quz', 'bo'),
		'quz-EC'         => array('runa shimi (Ecuador Suyu)', 'quz', 'ec'),
		'quz-PE'         => array('runasimi (Peru)', 'quz', 'pe'),
		'rm-CH'          => array('Rumantsch (Svizra)', 'rm', 'ch'),
		'ro-MD'          => array('română (Republica Moldova)', 'ro', 'md'),
		'ro-RO'          => array('română (România)', 'ro', 'ro'),
		'ru-BY'          => array('русский (Белорусия)', 'ru', 'by'),
		'ru-RU'          => array('русский (Россия)', 'ru', 'ru'),
		'rw-RW'          => array('Kinyarwanda (Rwanda)', 'rw', 'rw'),
		'sa-IN'          => array('संस्कृत (भारतम्)', 'sa', 'in'),
		'sd-Arab-PK'     => array('سنڌي (پاکستان)', 'sd', 'pk'),
		'se-FI'          => array('davvisámegiella (Suopma)', 'se', 'fi'),
		'se-NO'          => array('davvisámegiella (Norga)', 'se', 'no'),
		'se-SE'          => array('davvisámegiella (Ruoŧŧa)', 'se', 'se'),
		'sk-SK'          => array('slovenčina (Slovenská republika)', 'sk', 'sk'),
		'sl-SI'          => array('slovenščina (Slovenija)', 'sl', 'si'),
		'sma-NO'         => array('åarjelsaemiengïele (Nöörje)', 'sma', 'no'),
		'sma-SE'         => array('åarjelsaemiengïele (Sveerje)', 'sma', 'se'),
		'smj-NO'         => array('julevusámegiella (Vuodna)', 'smj', 'no'),
		'smj-SE'         => array('julevusámegiella (Svierik)', 'smj', 'se'),
		'smn-FI'         => array('sämikielâ (Suomâ)', 'smn', 'fi'),
		'sms-FI'         => array('sää´mǩiõll (Lää´ddjânnam)', 'sms', 'fi'),
		'sn-Latn-ZW'     => array('chiShona (Latin, Zimbabwe)', 'sn', 'zw'),
		'so-SO'          => array('Soomaali (Soomaaliya)', 'so', 'so'),
		'sq-AL'          => array('Shqip (Shqipëria)', 'sq', 'al'),
		'sr-Cyrl-BA'     => array('српски (Босна и Херцеговина)', 'sr', 'ba'),
		'sr-Cyrl-CS'     => array('српски (Србија и Црна Гора (Бивша))', 'sr', 'cs'),
		'sr-Cyrl-ME'     => array('српски (Црна Гора)', 'sr', 'me'),
		'sr-Cyrl-RS'     => array('српски (Србија)', 'sr', 'rs'),
		'sr-Latn-BA'     => array('srpski (Bosna i Hercegovina)', 'sr', 'ba'),
		'sr-Latn-CS'     => array('srpski (Srbija i Crna Gora (Bivša))', 'sr', 'cs'),
		'sr-Latn-ME'     => array('srpski (Crna Gora)', 'sr', 'me'),
		'sr-Latn-RS'     => array('srpski (Srbija)', 'sr', 'rs'),
		'st-ZA'          => array('Sesotho (South Africa)', 'st', 'za'),
		'sv-FI'          => array('svenska (Finland)', 'sv', 'fi'),
		'sv-SE'          => array('svenska (Sverige)', 'sv', 'se'),
		'sw-KE'          => array('Kiswahili (Kenya)', 'sw', 'ke'),
		'syr-SY'         => array('ܣܘܪܝܝܐ (ܣܘܪܝܐ)', 'syr', 'sy'),
		'ta-IN'          => array('தமிழ் (இந்தியா)', 'ta', 'in'),
		'ta-LK'          => array('தமிழ் (இலங்கை)', 'ta', 'lk'),
		'te-IN'          => array('తెలుగు (భారత దేశం)', 'te', 'in'),
		'tg-Cyrl-TJ'     => array('Тоҷикӣ (Тоҷикистон)', 'tg', 'tj'),
		'th-TH'          => array('ไทย (ไทย)', 'th', 'th'),
		'ti-ER'          => array('ትግርኛ (ኤርትራ)', 'ti', 'er'),
		'ti-ET'          => array('ትግርኛ (ኢትዮጵያ)', 'ti', 'et'),
		'tk-TM'          => array('Türkmen dili (Türkmenistan)', 'tk', 'tm'),
		'tn-BW'          => array('Setswana (Botswana)', 'tn', 'bw'),
		'tn-ZA'          => array('Setswana (Aforika Borwa)', 'tn', 'za'),
		'tr-TR'          => array('Türkçe (Türkiye)', 'tr', 'tr'),
		'ts-ZA'          => array('Xitsonga (South Africa)', 'ts', 'za'),
		'tt-RU'          => array('Татар (Россия)', 'tt', 'ru'),
		'tzm-Latn-DZ'    => array('Tamazight (Djazaïr)', 'tzm', 'dz'),
		'tzm-Tfng-MA'    => array('ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)', 'tzm', 'ma'),
		'ug-CN'          => array('ئۇيغۇرچە (جۇڭخۇا خەلق جۇمھۇرىيىتى)', 'ug', 'cn'),
		'uk-UA'          => array('українська (Україна)', 'uk', 'ua'),
		'ur-IN'          => array('اردو (بھارت)', 'ur', 'in'),
		'ur-PK'          => array('اُردو (پاکستان)', 'ur', 'pk'),
		'uz-Cyrl-UZ'     => array('Ўзбекча (Ўзбекистон Республикаси)', 'uz', 'uz'),
		'uz-Latn-UZ'     => array('O`zbekcha (O`zbekiston Respublikasi)', 'uz', 'uz'),
		'vi-VN'          => array('Tiếng Việt (Việt Nam)', 'vi', 'vn'),
		'wo-SN'          => array('Wolof (Senegaal)', 'wo', 'sn'),
		'xh-ZA'          => array('isiXhosa (uMzantsi Afrika)', 'xh', 'za'),
		'yo-NG'          => array('Yoruba (Nigeria)', 'yo', 'ng'),
		'zgh-Tfng-MA'    => array('ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)', 'zgh', 'ma'),
		'zh-CN'          => array('中文(中华人民共和国)', 'zh', 'cn'),
		'zh-HK'          => array('中文(香港特別行政區)', 'zh', 'hk'),
		'zh-MO'          => array('中文(澳門特別行政區)', 'zh', 'mo'),
		'zh-SG'          => array('中文(新加坡)', 'zh', 'sg'),
		'zh-TW'          => array('中文(台灣)', 'zh', 'tw'),
		'zu-ZA'          => array('isiZulu (iNingizimu Afrika)', 'zu', 'za')
	); 
	
	function __construct(string $LanguageSystem, string $UrlHost, string $NameHost, int $ThemeSustem = 0) {
		$this->TimeZone = \DateTimeZone::listIdentifiers();
		$this->LanguageHTML = $LanguageSystem;
		$this->Themes = scandir(\KYG_PATH_EXTERNAL . 'components' . DIRECTORY_SEPARATOR . 'jqueryui' . DIRECTORY_SEPARATOR . 'themes');
		parent::__construct();
        $this->setTemplateDir(\KYG_PATH_TEMPLATES);
        $this->setCompileDir(\KYG_PATH_TEMPLATES_C);
        $this->setConfigDir(\KYG_PATH_CONFIG);
        $this->setCacheDir(\KYG_PATH_CACHE);
		$this->addPluginsDir(\KYG_PATH_EXTERNAL . 'smarty-gettext' . DIRECTORY_SEPARATOR . 'smarty-gettext' . DIRECTORY_SEPARATOR);
		$this->left_delimiter = '{{';
		$this->right_delimiter = '}}';
		//$this->caching = \Smarty::CACHING_LIFETIME_CURRENT;
		$this->assign('Theme', $this->Themes[$ThemeSustem]);
		$this->assign('Themes', $this->Themes);
		$this->assign('LanguageSystem', $LanguageSystem);
        $this->assign('LanguagePage', $this->LanguageList[$LanguageSystem][1]);
		$this->assign('LanguageList', $this->LanguageList);
		$this->assign('Url', $UrlHost);
		$this->assign('Domain', $NameHost);
		$this->assign('TimeZone', $this->TimeZone);
	}
}